// Ankit's CV data as fallback when backend is unavailable
export const MOCK_DATA = {
  profile: {
    name: 'Ankit',
    tagline: 'Full Stack Developer',
    bio: "I'm a Computer Science student and a Full Stack Developer who loves turning ideas into reality. I enjoy building scalable web applications, exploring AI, and constantly learning new technologies.",
    email: 'ankitghanghas29@gmail.com',
    phone: '+91 9306992676',
    location: 'Phagwara, Punjab, India',
    availability: 'Open to work',
    freelance: 'Available',
    github: 'https://github.com/ankit-151',
    linkedin: 'https://www.linkedin.com/in/ankit1525',
    twitter: '',
    resume_url: '',
    profile_image: '/profile.jpg',
    hero_code_snippet: `const developer = {
  name: "Ankit",
  role: "Full Stack Developer",
  skills: ["React", "Node.js", "Python", "PHP"],
  passion: "Building products that solve real\n  problems",
  currently: "Open to exciting opportunities"
};

console.log(developer);`,

    stats: [
      { label: 'Years Learning', value: '2+', order: 0 },
      { label: 'Projects Completed', value: '5+', order: 1 },
      { label: 'Certifications', value: '3+', order: 2 },
      { label: 'GitHub Repos', value: '10+', order: 3 },
    ]
  },
  skills: [
    { _id: '1', name: 'React.js', category: 'frontend', level: 'Advanced', percentage: 85, icon_color: '#61DAFB' },
    { _id: '2', name: 'Next.js', category: 'frontend', level: 'Intermediate', percentage: 70, icon_color: '#000000' },
    { _id: '3', name: 'HTML', category: 'frontend', level: 'Advanced', percentage: 90, icon_color: '#E34F26' },
    { _id: '4', name: 'CSS', category: 'frontend', level: 'Advanced', percentage: 85, icon_color: '#1572B6' },
    { _id: '5', name: 'Tailwind CSS', category: 'frontend', level: 'Advanced', percentage: 80, icon_color: '#06B6D4' },
    { _id: '6', name: 'Node.js', category: 'backend', level: 'Advanced', percentage: 82, icon_color: '#339933' },
    { _id: '7', name: 'Express.js', category: 'backend', level: 'Advanced', percentage: 80, icon_color: '#000000' },
    { _id: '8', name: 'PHP', category: 'backend', level: 'Intermediate', percentage: 65, icon_color: '#777BB4' },
    { _id: '9', name: 'REST APIs', category: 'backend', level: 'Advanced', percentage: 83, icon_color: '#FF6B35' },
    { _id: '10', name: 'MongoDB', category: 'database', level: 'Advanced', percentage: 80, icon_color: '#47A248' },
    { _id: '11', name: 'MySQL', category: 'database', level: 'Intermediate', percentage: 70, icon_color: '#4479A1' },
    { _id: '12', name: 'JavaScript', category: 'languages', level: 'Advanced', percentage: 87, icon_color: '#F7DF1E' },
    { _id: '13', name: 'Python', category: 'languages', level: 'Intermediate', percentage: 72, icon_color: '#3776AB' },
    { _id: '14', name: 'Java', category: 'languages', level: 'Intermediate', percentage: 68, icon_color: '#ED8B00' },
    { _id: '15', name: 'C++', category: 'languages', level: 'Intermediate', percentage: 70, icon_color: '#00599C' },
    { _id: '16', name: 'C', category: 'languages', level: 'Intermediate', percentage: 65, icon_color: '#A8B9CC' },
    { _id: '17', name: 'Git', category: 'tools', level: 'Advanced', percentage: 85, icon_color: '#F05032' },
    { _id: '18', name: 'Postman', category: 'tools', level: 'Advanced', percentage: 80, icon_color: '#FF6C37' },
    { _id: '19', name: 'AWS', category: 'tools', level: 'Beginner', percentage: 50, icon_color: '#FF9900' },
    { _id: '20', name: 'Firebase', category: 'tools', level: 'Intermediate', percentage: 65, icon_color: '#FFCA28' },
    { _id: '21', name: 'OpenAI API', category: 'ai_ml', level: 'Intermediate', percentage: 68, icon_color: '#412991' },
    { _id: '22', name: 'Generative AI', category: 'ai_ml', level: 'Intermediate', percentage: 65, icon_color: '#4285F4' },
  ],
  projects: [
    {
      _id: 'p1',
      title: 'NutriAI',
      description: 'An AI-based nutrition monitoring application that enables users to track calorie intake and receive real-time nutritional analysis. Integrated the OpenAI API to generate personalized meal recommendations and nutritional insights based on user food logs.',
      image: '',
      tags: [
        { name: 'React Native', color: '#61DAFB' },
        { name: 'MongoDB', color: '#47A248' },
        { name: 'Node.js', color: '#339933' },
        { name: 'AI', color: '#9C27B0' },
      ],
      tech_stack: ['JavaScript (ES6+)', 'React.js', 'Node.js', 'Express.js', 'MongoDB', 'OpenAI API'],
      live_url: 'https://nutriai-example.vercel.app',
      github_url: 'https://github.com/ankit-151',
      featured: true,
    },
    {
      _id: 'p2',
      title: 'Patient Triage Management',
      description: 'A full-stack Patient Triage Management System based on Data Structures and Algorithms to automate patient prioritization. Designed a priority queue-based severity rating system to decrease emergency response time.',
      image: '',
      tags: [
        { name: 'PHP', color: '#777BB4' },
        { name: 'MySQL', color: '#4479A1' },
        { name: 'Tailwind CSS', color: '#06B6D4' },
      ],
      tech_stack: ['PHP', 'HTML', 'Tailwind CSS', 'MySQL', 'C++'],
      live_url: '',
      github_url: 'https://github.com/ankit-151',
      featured: true,
    },
  ],
  experience: [
    { _id: 'e1', title: 'Full Stack Developer', company: 'Self-Employed / Freelance', period: '2026 - Present', current: true },
    { _id: 'e2', title: 'Frontend & Backend', company: 'Full Stack Development', period: '2025', current: false },
    { _id: 'e3', title: 'Frontend Developer', company: 'Learning & Projects', period: '2024', current: false },
    { _id: 'e4', title: 'Started Coding', company: 'Self-Study', period: '2023 - 2024', current: false },
  ],
  certificates: [
    { _id: 'c1', title: 'Master Generative AI & Generative AI Tools (ChatGPT & more)', issuer: 'Udemy', issuer_logo: 'udemy', issuer_color: '#A435F0', date: 'Aug 2025', url: 'https://udemy.com' },
    { _id: 'c2', title: 'Cloud Computing', issuer: 'NPTEL', issuer_logo: 'nptel', issuer_color: '#FF5722', date: 'Nov 2024', url: 'https://nptel.ac.in' },
    { _id: 'c3', title: 'Mastering Data Structures and Algorithms', issuer: 'Lovely Professional University', issuer_logo: 'lpu', issuer_color: '#1565C0', date: 'Jul 2024', url: 'https://lpu.in' },
  ],
  achievements: [
    { _id: 'a1', label: 'LeetCode Problems', value: '100+', icon: 'code', is_stat: true },
    { _id: 'a2', label: 'GitHub Repos', value: '10+', icon: 'github', is_stat: true },
    { _id: 'a3', label: 'Projects Completed', value: '5+', icon: 'projects', is_stat: true },
    { _id: 'a4', label: 'Technologies', value: '15+', icon: 'tech', is_stat: true },
    { _id: 'a5', label: 'Hackathon Top 10', value: '1', icon: 'trophy', description: 'Top 10 in Code-a-Hunt Hackathon', is_stat: false },
    { _id: 'a6', label: 'Outlier AI Tasks', value: '50+', icon: 'star', description: 'AI data annotation tasks on Outlier (Mar 2025)', is_stat: false },
  ],
  education: [],
  training: [],
};
